### ISSUE TITLE
Export HTML rendering functions

### ISSUE THREAD

**Issue by bennycode** [hexojs/hexo-tag-embed#1]
Hello, I would like to re-use your HTML rendering functionality (like [here](https://github.com/hexojs/hexo-tag-embed/blob/v1.0.0-rc.1/lib/tags/youtube.ts)) in a Remark Plugin, so that I can support Hexo's embed tags in other systems (like [Docusaurus](https://docusaurus.io/) or [Astro](https://astro.build/)). 😀

Currently I am doing it like this:

```js
import { visit } from 'unist-util-visit';
import { youtubeTag } from 'hexo-tag-embed/dist/tags/youtube';

export default function plugin(options) {
  const transformer = async (ast) => {
    visit(ast, 'text', (node) => {
      const { value } = node;

      if (value.startsWith(`{% youtube `)) {
        node.type = `html`;
        node.value = youtubeTag(['TEST-VIDEO-ID', 'video', false]);
      }
    });
  };

  return transformer;
}
```

The path of `hexo-tag-embed/dist/tags/youtube` looks a little funky. Would it be possible to re-export that `youtubeTag` function (and related) from your `index.ts` file as well so I could do the following?

```js
import { youtubeTag } from 'hexo-tag-embed';
```

**Comment by bennycode** [comment]
@yoshinorin do you know how a code like `{% youtube 62J_eQsK0e0?start=531 'video' false %}` is actually parsed into `['62J_eQsK0e0?start=531', 'video', false]`? Is there a hexo utility library available?

**Comment by uiolee** [comment]
> do you know how a code like `{% youtube 62J_eQsK0e0?start=531 'video' false %}` is actually parsed into `['62J_eQsK0e0?start=531', 'video', false]`? Is there a hexo utility library available?

I guess this step is handled by `nunjucks`。
https://github.com/hexojs/hexo/blob/7b588e78aae57e756e4d18bcd78e63d9dc7d34cd/lib/extend/tag.ts#L264-L273

**Comment by bennycode** [comment]
Ah, the syntax is coming from [Swig](https://node-swig.github.io/swig-templates/), that's interesting to know! 💡 Thank you! 🙇
